name: jsPalette
author: reednj
category: Widgets
tags: [color, palette]
docs: https://github.com/reednj/jsPalette/blob/master/readme.md
demo: http://popacular.com/jspalette/Test/demo.html
current: v1.0
